pragma foreign_keys = ON;
CREATE TABLE `models` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`path` TEXT NOT NULL UNIQUE
);
CREATE TABLE `vec4` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`x` REAL NOT NULL,
	`y` REAL NOT NULL,
	`z` REAL NOT NULL,
	`w` REAL NOT NULL
);
CREATE TABLE `vec3` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`x` REAL NOT NULL,
	`y` REAL NOT NULL,
	`z` REAL NOT NULL
);
CREATE TABLE `vec2` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`x` REAL NOT NULL,
	`y` REAL NOT NULL
);
CREATE TABLE `triplanars` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`colour_1` INTEGER NOT NULL,
	`colour_2` INTEGER NOT NULL,
	`colour_3` INTEGER NOT NULL,
	`colour_4` INTEGER NOT NULL,
	`blends` INTEGER NOT NULL,
	`scales` INTEGER NOT NULL,
	`positions` INTEGER NOT NULL,
	FOREIGN KEY (colour_1) REFERENCES vec4(id),
	FOREIGN KEY (colour_2) REFERENCES vec4(id)
	FOREIGN KEY (colour_3) REFERENCES vec4(id),
	FOREIGN KEY (colour_4) REFERENCES vec4(id)
	FOREIGN KEY (blends) REFERENCES vec3(id),
	FOREIGN KEY (scales) REFERENCES vec3(id),
	FOREIGN KEY (positions) REFERENCES vec2(id)
);
CREATE TABLE `terrains` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`position` INTEGER NOT NULL,
	`model_id` INTEGER NOT NULL,
	`shader_id` INTEGER NOT NULL,
	FOREIGN KEY (model_id) REFERENCES models(id),
	FOREIGN KEY (shader_id)	REFERENCES triplanars(id),
	FOREIGN KEY (position) REFERENCES vec3(id)
);
