#pragma once

namespace noob
{
enum class key_type { SPACE, APOSTROPHE, COMMA, MINUS, PERIOD, SLASH, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, SEMICOLON, EQUAL, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V ,W, X, Y, Z, LEFT_BRACKET, BACKSLASH, RIGHT_BRACKET, GRAVE_ACCENT, ESC, ENTER, TAB, BACKSPACE, INSERT, DELETE, RIGHT_ARROW, LEFT_ARROW, DOWN_ARROW, UP_ARROW, PAGE_UP, PAGE_DOWN, HOME, END, CAPLOCK, SCROLL_LOCK, NUM_LOCK, PRINT_SCREEN, PAUSE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5, NUMPAD_6, NUMPAD_7, NUMPAD_8, NUMPAD_9, NUMPAD_DOT, NUMPAD_DIV, NUMPAD_MULT, NUMPAD_SUB, NUMPAD_ADD, NUMPAD_ENTER, NUMPAD_EQUAL, SHIFT_LEFT, CTRL_LEFT, ALT_LEFT, SUPER_LEFT, SHIFT_RIGHT, CTRL_RIGHT, ALT_RIGHT, SUPER_RIGHT, MENU, UNKNOWN};

enum class key_state { PRESS, RELEASE, REPEAT, UNKNOWN };

}
