

// enum class tex_params { TEXTURE_BASE_LEVEL, TEXTURE_COMPARE_FUNC, TEXTURE_COMPARE_MODE, TEXTURE_MIN_FILTER, TEXTURE_MAG_FILTER, TEXTURE_MIN_LOD, TEXTURE_MAX_LOD, TEXTURE_MAX_LEVEL, TEXTURE_SWIZZLE_R, TEXTURE_SWIZZLE_G, TEXTURE_SWIZZLE_B, TEXTURE_SWIZZLE_A, TEXTURE_WRAP_S, TEXTURE_WRAP_T, TEXTURE_WRAP_R };


