#pragma once

#include "RegisterMath.hpp"
#include "RegisterPlane.hpp"
#include "RegisterGraphics.hpp"
#include "RegisterControls.hpp"
#include "RegisterBasicMesh.hpp"
#include "RegisterActiveMesh.hpp"
#include "RegisterGlobals.hpp"
#include "RegisterStage.hpp"
#include "RegisterLight.hpp"
#include "RegisterReflectance.hpp"
#include "RegisterVoxels.hpp"
#include "RegisterScaledModel.hpp"
#include "RegisterHandles.hpp"
#include "RegisterBody.hpp"
#include "RegisterJoint.hpp"
#include "RegisterUniforms.hpp"
