#APP_ARM_MODE := arm
APP_CPPFLAGS += -std=c++11 -frtti -fexceptions -fpermissive -DASIO_STANDALONE -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DBGFX_CONFIG_MULTITHREADED=0# -DBX_PLATFORM_ANDROID=1 -DBGFX_USE_EGL=1 -DBGFX_CONFIG_RENDERER_OPENGLES=30
APP_STL := gnustl_static
APP_ABI := all
#NDK_TOOLCHAIN := androideabi4.9 
