include_directories(lib/bullet/src)
include_directories(lib/bullet/BulletCollision)

list (APPEND main_src
	lib/bullet/src/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp
	lib/bullet/src/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp
	lib/bullet/src/BulletDynamics/Dynamics/Bullet-C-API.cpp
	lib/bullet/src/BulletDynamics/Dynamics/btRigidBody.cpp
	lib/bullet/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp
	lib/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp
	lib/bullet/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBody.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp
	lib/bullet/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp
	lib/bullet/src/BulletDynamics/Character/btKinematicCharacterController.cpp
	lib/bullet/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp
	lib/bullet/src/BulletDynamics/Vehicle/btWheelInfo.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp
	lib/bullet/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btGhostObject.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btUnionFind.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/Gimpact/gim_box_set.cpp
	lib/bullet/src/BulletCollision/Gimpact/gim_contact.cpp
	lib/bullet/src/BulletCollision/Gimpact/btGImpactShape.cpp
	lib/bullet/src/BulletCollision/Gimpact/gim_tri_collision.cpp
	lib/bullet/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp
	lib/bullet/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp
	lib/bullet/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp
	lib/bullet/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp
	lib/bullet/src/BulletCollision/Gimpact/btContactProcessing.cpp
	lib/bullet/src/BulletCollision/Gimpact/gim_memory.cpp
	lib/bullet/src/BulletCollision/Gimpact/btGImpactBvh.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btCompoundShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btBoxShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btShapeHull.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btBox2dShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConeShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btEmptyShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btCylinderShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btSphereShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp
	lib/bullet/src/BulletCollision/CollisionShapes/btConcaveShape.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btDbvt.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp
	lib/bullet/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp
	lib/bullet/src/LinearMath/btQuickprof.cpp
	lib/bullet/src/LinearMath/btAlignedAllocator.cpp
	lib/bullet/src/LinearMath/btSerializer.cpp
	lib/bullet/src/LinearMath/btPolarDecomposition.cpp
	lib/bullet/src/LinearMath/btConvexHull.cpp
	lib/bullet/src/LinearMath/btGeometryUtil.cpp
	lib/bullet/src/LinearMath/btConvexHullComputer.cpp
	lib/bullet/src/LinearMath/btVector3.cpp
	lib/bullet/src/BulletSoftBody/btDefaultSoftBodySolver.cpp
	lib/bullet/src/BulletSoftBody/btSoftBody.cpp
	lib/bullet/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp
	lib/bullet/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp
	lib/bullet/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp
	lib/bullet/src/BulletSoftBody/btSoftRigidDynamicsWorld.cpp
	lib/bullet/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp
	lib/bullet/src/BulletSoftBody/btSoftBodyHelpers.cpp
	lib/bullet/src/BulletMultiThreaded/btParallelConstraintSolver.cpp
	lib/bullet/src/BulletMultiThreaded/SpuSampleTaskProcess.cpp
	lib/bullet/src/BulletMultiThreaded/SpuLibspe2Support.cpp
	lib/bullet/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.cpp
	lib/bullet/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/boxBoxDistance.cpp
	lib/bullet/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuContactResult.cpp
	lib/bullet/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuMinkowskiPenetrationDepthSolver.cpp
	lib/bullet/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuCollisionShapes.cpp
	lib/bullet/src/BulletMultiThreaded/Win32ThreadSupport.cpp
	lib/bullet/src/BulletMultiThreaded/SpuFakeDma.cpp
	lib/bullet/src/BulletMultiThreaded/SpuCollisionTaskProcess.cpp
	lib/bullet/src/BulletMultiThreaded/PosixThreadSupport.cpp
	lib/bullet/src/BulletMultiThreaded/btThreadSupportInterface.cpp
	lib/bullet/src/BulletMultiThreaded/SpuContactManifoldCollisionAlgorithm.cpp
	lib/bullet/src/BulletMultiThreaded/SequentialThreadSupport.cpp
	lib/bullet/src/BulletMultiThreaded/SpuCollisionObjectWrapper.cpp
	lib/bullet/src/BulletMultiThreaded/SpuGatheringCollisionDispatcher.cpp
	lib/bullet/src/BulletMultiThreaded/btGpu3DGridBroadphase.cpp
	lib/bullet/src/BulletMultiThreaded/SpuSampleTask/SpuSampleTask.cpp
	)
#########################
#
# Consciously excluded:
#
#########################
#
# lib/bullet/src/MiniCL/MiniCL.cpp
# lib/bullet/src/MiniCL/MiniCLTask/MiniCLTask.cpp
# lib/bullet/src/MiniCL/MiniCLTaskScheduler.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/DX11/btSoftBodySolver_DX11SIMDAware.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/DX11/btSoftBodySolver_DX11.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/btSoftBodySolver_OpenCL.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/btSoftBodySolverOutputCLtoGL.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/btSoftBodySolver_OpenCLSIMDAware.cpp
# lib/bullet/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/MiniCL/MiniCLTaskWrap.cpp


